name: Update Pac-Man Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Switch to output branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git fetch origin
          git switch --create output || git switch output

      - name: Copy Pac-Man SVGs to root
        run: |
          rm -rf *
          cp -r pacman-assets/*.svg .  # Make sure this path matches where your SVGs are

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Update Pac-Man contribution graph" || echo "No changes to commit"
          git push origin output
