name: Generate Pac-Man Contribution Graph

on:
  # Run the workflow once a day at midnight
  schedule:
    - cron: '0 0 * * *'
  # Also run it when the workflow file is pushed or manually triggered
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python if your Pac-Man script uses it
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies (adjust if not using requirements.txt)
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Run your Pac-Man script (replace with actual command)
      - name: Generate Pac-Man animation
        run: |
          python generate_pacman.py  # Replace with your actual script

      # Commit and push the generated SVG to the `output` branch
      - name: Push output to the output branch
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git checkout --orphan output
          git rm -rf .
          mv path/to/generated/*.svg .  # Update path accordingly
          git add .
          git commit -m "Update Pac-Man contribution graph"
          git push -f origin output
